INSERT INTO PUBLISHERS (NAME, EMAIL, PHONE) VALUES ('Publisher A', 'publisher@a.com', '(123) 456-7890')
INSERT INTO PUBLISHERS (NAME, EMAIL, PHONE) VALUES ('Publisher B', 'publisher@b.com', '(123) 456-0987')
INSERT INTO PUBLISHERS (NAME, EMAIL, PHONE) VALUES ('Publisher C', 'publisher@c.com', '(123) 654-7890')

INSERT INTO AUTHORING_ENTITIES (NAME, AUTHORING_ENTITY_TYPE, EMAIL, HEADWRITER, YEARFORMED) VALUES ('Writing Group A', 'WritingGroup', 'writing@groupa.com', 'John Smith', 2008)
INSERT INTO AUTHORING_ENTITIES (NAME, AUTHORING_ENTITY_TYPE, EMAIL, HEADWRITER, YEARFORMED) VALUES ('Individual Author A', 'IndividualAuthor', 'individual@authora.com', NULL, NULL)
INSERT INTO AUTHORING_ENTITIES (NAME, AUTHORING_ENTITY_TYPE, EMAIL, HEADWRITER, YEARFORMED) VALUES ('Ad Hoc Team A', 'AdHocTeam', 'adhoc@teama.com', NULL, NULL)

INSERT INTO BOOKS (ISBN, TITLE, YEAR_PUBLISHED, AUTHORING_ENTITY_NAME, PUBLISHER_NAME) VALUES ('12345678987654321', 'The Best Book', 2010, 'Writing Group A', 'Publisher A')
INSERT INTO BOOKS (ISBN, TITLE, YEAR_PUBLISHED, AUTHORING_ENTITY_NAME, PUBLISHER_NAME) VALUES ('98765432123456789', 'The Second Best Book', 2011, 'Individual Author A', 'Publisher B')
INSERT INTO BOOKS (ISBN, TITLE, YEAR_PUBLISHED, AUTHORING_ENTITY_NAME, PUBLISHER_NAME) VALUES ('12345678987654321', 'The Third Best Book', 2012, 'Ad Hoc Team A', 'Publisher C')